### PR TITLE
/users ordered by number of presentations given

### PR DESCRIPTION
**Pull request by padi**
... to encourage more speakers to present in the monthly meetups.

Why I think this is important:

1. The https://pinoyrb.org/users page is part of what has driven me to start speaking up in meetups. Countless talks haven been given by me since then, good and bad.
2. Making the list of contributors in http://contributors.rubyonrails.org/ is part of what helped others to start contributing to the repo. I reckon that if we include this as part of our call for speakers in the next (and final) meetup of the year, we'll encourage more people to volunteer as speakers.

### CODE REVIEW

**Comment by terenceponce** [comment]
Fine by my. How about @bryanbibat?

**Comment by padi** [comment]
I also manually tested this by updating the `db/seeds.rb` file, but not sure if it's worth merging in the seeds.rb or it's better suited as an rspec test:

```ruby
+AdminUser.create(email: 'admin@pinoyrb.org', password: 'pinoyrborg')
+
+# Creates Ruby users, presentations and events where the presentations were held.
+(1..10).each do |n|
+  user = User.create!(name: "Ruby User #{n}", email: "user_#{n}@pinoyrb.org", password: 'pinoyrborg')
+  n.times do |presentation_count|
+    event = Event.find_or_create_by!(name: "Event #{presentation_count}", event_type: 'meetup')
+    presentation = Presentation.create!(name: "Presentation #{presentation_count}", event: event)
+    Speaker.create!(presentation: presentation, user: user)
+  end
+end
```

**Comment by bryanbibat** [comment]
LGTM 👍 

Both adding it to seed and creating a simple spec to test it may be the best approach.

**Comment by padi** [comment]
Added controller test and seed data. :+1:

**Comment by bryanbibat** [comment]
LGTM, @terenceponce please check and merge if it's ok with you. I'll deploy the changes once merged.

**Comment by terenceponce** [comment]
Looks great! Merging it now

**Comment by bryanbibat** [comment]
Deployed, see http://pinoyrb.org/users

**Pull request merged**
